export const state = () => ({
  // products items list
  products: [
    {img:'1',title:'آیفون 13 پرو مکس',text:'ایفون 13 پرو مکس 256 گیگ حافظه',qemat:'48 میلیون',grup:'janbe'},
    {img:'2',title:'روغن غنچه',text:'روغن سرخ کردنی غنچه',qemat:'23,000',grup:'xorake'},
    {img:'3',title:'برنج طبیعت',text:'برنج دانه بلند طبیعت',qemat:'450,000',grup:'xorake',},
    {img:'4',title:'روغن لادن',text:'روغن 4 کیلویی لادن',qemat:'80,000',off:'',grup:'xorake',},
    {img:'5',title:'ساعت سامسونگ',text:'ساعت هوشمند برند سامسونگ',qemat:'4 میلیون',grup:'janbe',},
    {img:'6',title:'دریل شارژی',text:'مینی دریل شارژی',qemat:'2,5 میلیون',grup:'sanate',},
    {img:'7',title:'آچار فرانسه',text:'آچار فرانسه مشکی',qemat:'200,000',grup:'sanate',},
    {img:'8',title:'اپل واچ',text:'ساعت هوشمند برند اپل',qemat:'5,5 میلیون',grup:'janbe',},
    {img:'9',title:'ایرپاد',text:'ایرپاد مشکی شیاومی',qemat:'600,000',grup:'janbe',},
    {img:'10',title:'برنج خوشبخت',text:'برنج دانه بلند خوشبخت',qemat:'420,000',grup:'xorake',},
    {img:'11',title:'شیاومی mi11',text:'شیاومی می 11 آبی',qemat:'18 میلیون',grup:'janbe',},
    {img:'12',title:'روغن موتور',text:'روغن موتور خارجی',qemat:'110,000',grup:'sanate',},
    {img:'13',title:'یخچال',text:'یخچال بالا پایین',qemat:'33 میلیون',grup:'xange',},
    {img:'14',title:'یخچال',text:'یخچال دوقلو',qemat:'50 میلیون',grup:'xange',},
    {img:'15',title:'قابلمه',text:'قابلمه نسوز ',qemat:'16,000',grup:'xange',},
    {img:'16',title:'شارژر',text:'شارژر فست مدل ravpower',qemat:'1 میلیون',grup:'janbe',},
    {img:'17',title:'دنت',text:'دنت با طعم توت فرنگی',qemat:'10,000',grup:'xorake',},
    {img:'18',title:'ال ای دی',text:' ال ای دی 65 اینچ',qemat:'17 میلیون',grup:'xange',},
    {img:'19',title:'آچار بکس',text:'آچار بکس جغجغه ای',qemat:'300,000',grup:'sanate',},
    {img:'20',title:'اره برقی',text:'اره برقی دو تیغ',qemat:'1,6 میلیون',grup:'sanate',},
    {img:'21',title:'اهم متر',text:'اهم متر دیجیتالی',qemat:'450,000',grup:'sanate',},
    {img:'22',title:'پفک',text:'پفک بزرگ',qemat:'6000',grup:'xorake',},
    {img:'23',title:'ال ای دی',text:' ال ای دی 70 اینچ',qemat:'20 میلیون',grup:'xange',},
    {img:'24',title:'چای',text:'چای معتر محمود',qemat:'100,000',grup:'xorake',},
    {img:'25',title:'چای',text:'چای محمود',qemat:'110,000',grup:'xorake',},
    {img:'26',title:'دریل',text:'مینی دریل',qemat:'1 میلیون',grup:'sanate',},
    {img:'27',title:'روغن موتور',text:'روغن موتور بهران',qemat:'160,000',grup:'sanate',},
    {img:'28',title:'روغن سرخ کردنی',text:'روغن سرخ کردنی',qemat:'35,000',grup:'xorake',},
    {img:'29',title:'ساعت دیواری',text:'ساعت دیواری بدون قاب',qemat:'110,000',grup:'xange',},
    {img:'30',title:'ساعت دیواری',text:'ساعت دیواری مدل چوبی',qemat:'170,000',grup:'xange',},
    {img:'31',title:'گوشی سامسونگ',text:'گوشی سامسونگ a32',qemat:'5 میلیون',grup:'janbe',},
    {img:'32',title:'فایل',text:'فایل چهار کشوی',qemat:'300,000',grup:'xange',},
    {img:'33',title:'قاب گوشی',text:' قاب ژله ای آیفون13',qemat:'80,000',grup:'janbe',},
    {img:'34',title:'قابلمه',text:'سری 7 تیکه نسوز',qemat:'1,5 میلیون',grup:'xange',},
    {img:'35',title:'لباسشویی',text:'لباسشویی 8 کیلویی سامسونگ',qemat:'12 میلیون',grup:'xange',},
    {img:'36',title:'لواشک',text:'لواشک بسته ای 50 عددی',qemat:'100,000',grup:'xorake',},
    {img:'37',title:'لباسشویی',text:'لباسشویی 5 کیلویی سامسونگ',qemat:'9 میلیون',grup:'xange',},
    {img:'38',title:'ایرپاد',text:'ایرپاد مدل 13kM ',qemat:'2 میلیون',grup:'janbe',},
    {img:'39',title:'ساعت',text:'ساعت مچی ',qemat:'1 میلیون',grup:'janbe',},
    {img:'40',title:'ایرپاد',text:'ایرپاد مدل 16kM ',qemat:'2 میلیون',grup:'janbe',},
    {img:'41',title:'کفش',text:' کفش مردانه',qemat:' 400,000',grup:'janbe',},
    {img:'42',title:'ظرف',text:' ظرف پلاستیکی ',qemat:'2 میلیون',grup:'xange',},
    {img:'43',title:'خودکار',text:'خودکار روان نویس ',qemat:' 95,000',grup:'janbe',},
    {img:'44',title:'کرم',text:'کرم الورا ',qemat:' 150,000',grup:'janbe',},
    {img:'45',title:'لباس',text:'لباس بچگانه',qemat:'200,000',grup:'janbe',},
    {img:'46',title:'دیگ',text:'دیگ زود پز ',qemat:'2 میلیون',grup:'xange',},
    {img:'47',title:'ساعت',text:'ساعت مچی ',qemat:'1 میلیون',grup:'janbe',},
    {img:'48',title:'دریل',text:'دریل صنعتی ',qemat:'10 میلیون',grup:'sanate',},
    {img:'49',title:'تخم مرغ',text:'تخم مرغ تازه',qemat:'20,000',grup:'xorake',},
    {img:'50',title:'ماکارونی',text:'ماکارونی زر ماکارون ',qemat:'40,000',grup:'xorake',},
  ]
})
